# This file is auto-generated by Swagger Codegen (https://github.com/swagger-api/swagger-codegen)
# Please replace "TEST_VALUE" with a proper value and uncomment the code for testing the function

Describe 'cloudmersiveConvert ConvertWebApi' {
    Context 'ConvertWebApi' {
        It 'Invoke-ConvertWebApiConvertWebHtmlToPdf' {
            $ret = Invoke-PetApiGetPetById -input "TEST_VALUE"
            #$ret | Should BeOfType cloudmersiveConvert.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

    Context 'ConvertWebApi' {
        It 'Invoke-ConvertWebApiConvertWebUrlToPdf' {
            $ret = Invoke-PetApiGetPetById -input "TEST_VALUE"
            #$ret | Should BeOfType cloudmersiveConvert.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

    Context 'ConvertWebApi' {
        It 'Invoke-ConvertWebApiConvertWebUrlToScreenshot' {
            $ret = Invoke-PetApiGetPetById -input "TEST_VALUE"
            #$ret | Should BeOfType cloudmersiveConvert.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

}
