# This file is auto-generated by Swagger Codegen (https://github.com/swagger-api/swagger-codegen)
# Please replace "TEST_VALUE" with a proper value and uncomment the code for testing the function

Describe 'cloudmersiveConvert ConvertImageApi' {
    Context 'ConvertImageApi' {
        It 'Invoke-ConvertImageApiConvertImageImageFormatConvert' {
            $ret = Invoke-PetApiGetPetById -format1 "TEST_VALUE" -format2 "TEST_VALUE" -inputFile "TEST_VALUE"
            #$ret | Should BeOfType cloudmersiveConvert.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

}
