# This file is auto-generated by Swagger Codegen (https://github.com/swagger-api/swagger-codegen)
# Please replace "TEST_VALUE" with a proper value and uncomment the code for testing the function

Describe 'cloudmersiveConvert ConvertDocumentApi' {
    Context 'ConvertDocumentApi' {
        It 'Invoke-ConvertDocumentApiConvertDocumentAutodetectToPdf' {
            $ret = Invoke-PetApiGetPetById -inputFile "TEST_VALUE"
            #$ret | Should BeOfType cloudmersiveConvert.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

    Context 'ConvertDocumentApi' {
        It 'Invoke-ConvertDocumentApiConvertDocumentDocxToPdf' {
            $ret = Invoke-PetApiGetPetById -inputFile "TEST_VALUE"
            #$ret | Should BeOfType cloudmersiveConvert.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

    Context 'ConvertDocumentApi' {
        It 'Invoke-ConvertDocumentApiConvertDocumentPptxToPdf' {
            $ret = Invoke-PetApiGetPetById -inputFile "TEST_VALUE"
            #$ret | Should BeOfType cloudmersiveConvert.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

    Context 'ConvertDocumentApi' {
        It 'Invoke-ConvertDocumentApiConvertDocumentXlsxToCsv' {
            $ret = Invoke-PetApiGetPetById -inputFile "TEST_VALUE"
            #$ret | Should BeOfType cloudmersiveConvert.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

    Context 'ConvertDocumentApi' {
        It 'Invoke-ConvertDocumentApiConvertDocumentXlsxToPdf' {
            $ret = Invoke-PetApiGetPetById -inputFile "TEST_VALUE"
            #$ret | Should BeOfType cloudmersiveConvert.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

}
