# This file is auto-generated by Swagger Codegen (https://github.com/swagger-api/swagger-codegen)
# Please replace "TEST_VALUE" with a proper value and uncomment the code for testing the function

Describe 'cloudmersiveConvert ConvertDataApi' {
    Context 'ConvertDataApi' {
        It 'Invoke-ConvertDataApiConvertDataCsvToJson' {
            $ret = Invoke-PetApiGetPetById -inputFile "TEST_VALUE"
            #$ret | Should BeOfType cloudmersiveConvert.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

    Context 'ConvertDataApi' {
        It 'Invoke-ConvertDataApiConvertDataXmlToJson' {
            $ret = Invoke-PetApiGetPetById -inputFile "TEST_VALUE"
            #$ret | Should BeOfType cloudmersiveConvert.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

}
