/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing HtmlTemplateOperation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HtmlTemplateOperationTests
    {
        // TODO uncomment below to declare an instance variable for HtmlTemplateOperation
        //private HtmlTemplateOperation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HtmlTemplateOperation
            //instance = new HtmlTemplateOperation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HtmlTemplateOperation
        /// </summary>
        [Test]
        public void HtmlTemplateOperationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HtmlTemplateOperation
            //Assert.IsInstanceOfType<HtmlTemplateOperation> (instance, "variable 'instance' is a HtmlTemplateOperation");
        }


        /// <summary>
        /// Test the property 'Action'
        /// </summary>
        [Test]
        public void ActionTest()
        {
            // TODO unit test for the property 'Action'
        }
        /// <summary>
        /// Test the property 'MatchAgsint'
        /// </summary>
        [Test]
        public void MatchAgsintTest()
        {
            // TODO unit test for the property 'MatchAgsint'
        }
        /// <summary>
        /// Test the property 'ReplaceWith'
        /// </summary>
        [Test]
        public void ReplaceWithTest()
        {
            // TODO unit test for the property 'ReplaceWith'
        }

    }

}
