/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing HtmlToPdfRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HtmlToPdfRequestTests
    {
        // TODO uncomment below to declare an instance variable for HtmlToPdfRequest
        //private HtmlToPdfRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HtmlToPdfRequest
            //instance = new HtmlToPdfRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HtmlToPdfRequest
        /// </summary>
        [Test]
        public void HtmlToPdfRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HtmlToPdfRequest
            //Assert.IsInstanceOfType<HtmlToPdfRequest> (instance, "variable 'instance' is a HtmlToPdfRequest");
        }


        /// <summary>
        /// Test the property 'Html'
        /// </summary>
        [Test]
        public void HtmlTest()
        {
            // TODO unit test for the property 'Html'
        }
        /// <summary>
        /// Test the property 'ExtraLoadingWait'
        /// </summary>
        [Test]
        public void ExtraLoadingWaitTest()
        {
            // TODO unit test for the property 'ExtraLoadingWait'
        }

    }

}
