/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing HtmlTemplateApplicationRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HtmlTemplateApplicationRequestTests
    {
        // TODO uncomment below to declare an instance variable for HtmlTemplateApplicationRequest
        //private HtmlTemplateApplicationRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HtmlTemplateApplicationRequest
            //instance = new HtmlTemplateApplicationRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HtmlTemplateApplicationRequest
        /// </summary>
        [Test]
        public void HtmlTemplateApplicationRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HtmlTemplateApplicationRequest
            //Assert.IsInstanceOfType<HtmlTemplateApplicationRequest> (instance, "variable 'instance' is a HtmlTemplateApplicationRequest");
        }


        /// <summary>
        /// Test the property 'HtmlTemplate'
        /// </summary>
        [Test]
        public void HtmlTemplateTest()
        {
            // TODO unit test for the property 'HtmlTemplate'
        }
        /// <summary>
        /// Test the property 'HtmlTemplateUrl'
        /// </summary>
        [Test]
        public void HtmlTemplateUrlTest()
        {
            // TODO unit test for the property 'HtmlTemplateUrl'
        }
        /// <summary>
        /// Test the property 'Operations'
        /// </summary>
        [Test]
        public void OperationsTest()
        {
            // TODO unit test for the property 'Operations'
        }

    }

}
