/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing HtmlTemplateApplicationResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HtmlTemplateApplicationResponseTests
    {
        // TODO uncomment below to declare an instance variable for HtmlTemplateApplicationResponse
        //private HtmlTemplateApplicationResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HtmlTemplateApplicationResponse
            //instance = new HtmlTemplateApplicationResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HtmlTemplateApplicationResponse
        /// </summary>
        [Test]
        public void HtmlTemplateApplicationResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HtmlTemplateApplicationResponse
            //Assert.IsInstanceOfType<HtmlTemplateApplicationResponse> (instance, "variable 'instance' is a HtmlTemplateApplicationResponse");
        }


        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Test]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }
        /// <summary>
        /// Test the property 'FinalHtml'
        /// </summary>
        [Test]
        public void FinalHtmlTest()
        {
            // TODO unit test for the property 'FinalHtml'
        }

    }

}
