/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ConvertTemplateApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ConvertTemplateApiTests
    {
        private ConvertTemplateApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ConvertTemplateApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ConvertTemplateApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ConvertTemplateApi
            //Assert.IsInstanceOfType(typeof(ConvertTemplateApi), instance, "instance is a ConvertTemplateApi");
        }

        
        /// <summary>
        /// Test ConvertTemplateApplyHtmlTemplate
        /// </summary>
        [Test]
        public void ConvertTemplateApplyHtmlTemplateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //HtmlTemplateApplicationRequest value = null;
            //var response = instance.ConvertTemplateApplyHtmlTemplate(value);
            //Assert.IsInstanceOf<HtmlTemplateApplicationResponse> (response, "response is HtmlTemplateApplicationResponse");
        }
        
    }

}
