/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IConvertTemplateApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Apply HTML template
        /// </summary>
        /// <remarks>
        /// Apply operations to fill in an HTML template, generating a final HTML result
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">Operations to apply to template</param>
        /// <returns>HtmlTemplateApplicationResponse</returns>
        HtmlTemplateApplicationResponse ConvertTemplateApplyHtmlTemplate (HtmlTemplateApplicationRequest value);

        /// <summary>
        /// Apply HTML template
        /// </summary>
        /// <remarks>
        /// Apply operations to fill in an HTML template, generating a final HTML result
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">Operations to apply to template</param>
        /// <returns>ApiResponse of HtmlTemplateApplicationResponse</returns>
        ApiResponse<HtmlTemplateApplicationResponse> ConvertTemplateApplyHtmlTemplateWithHttpInfo (HtmlTemplateApplicationRequest value);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Apply HTML template
        /// </summary>
        /// <remarks>
        /// Apply operations to fill in an HTML template, generating a final HTML result
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">Operations to apply to template</param>
        /// <returns>Task of HtmlTemplateApplicationResponse</returns>
        System.Threading.Tasks.Task<HtmlTemplateApplicationResponse> ConvertTemplateApplyHtmlTemplateAsync (HtmlTemplateApplicationRequest value);

        /// <summary>
        /// Apply HTML template
        /// </summary>
        /// <remarks>
        /// Apply operations to fill in an HTML template, generating a final HTML result
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">Operations to apply to template</param>
        /// <returns>Task of ApiResponse (HtmlTemplateApplicationResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<HtmlTemplateApplicationResponse>> ConvertTemplateApplyHtmlTemplateAsyncWithHttpInfo (HtmlTemplateApplicationRequest value);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ConvertTemplateApi : IConvertTemplateApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ConvertTemplateApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ConvertTemplateApi(String basePath)
        {
            this.Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ConvertTemplateApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ConvertTemplateApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Apply HTML template Apply operations to fill in an HTML template, generating a final HTML result
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">Operations to apply to template</param>
        /// <returns>HtmlTemplateApplicationResponse</returns>
        public HtmlTemplateApplicationResponse ConvertTemplateApplyHtmlTemplate (HtmlTemplateApplicationRequest value)
        {
             ApiResponse<HtmlTemplateApplicationResponse> localVarResponse = ConvertTemplateApplyHtmlTemplateWithHttpInfo(value);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Apply HTML template Apply operations to fill in an HTML template, generating a final HTML result
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">Operations to apply to template</param>
        /// <returns>ApiResponse of HtmlTemplateApplicationResponse</returns>
        public ApiResponse< HtmlTemplateApplicationResponse > ConvertTemplateApplyHtmlTemplateWithHttpInfo (HtmlTemplateApplicationRequest value)
        {
            // verify the required parameter 'value' is set
            if (value == null)
                throw new ApiException(400, "Missing required parameter 'value' when calling ConvertTemplateApi->ConvertTemplateApplyHtmlTemplate");

            var localVarPath = "/convert/template/html/apply";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (value != null && value.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(value); // http body (model) parameter
            }
            else
            {
                localVarPostBody = value; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ConvertTemplateApplyHtmlTemplate", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<HtmlTemplateApplicationResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (HtmlTemplateApplicationResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(HtmlTemplateApplicationResponse)));
        }

        /// <summary>
        /// Apply HTML template Apply operations to fill in an HTML template, generating a final HTML result
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">Operations to apply to template</param>
        /// <returns>Task of HtmlTemplateApplicationResponse</returns>
        public async System.Threading.Tasks.Task<HtmlTemplateApplicationResponse> ConvertTemplateApplyHtmlTemplateAsync (HtmlTemplateApplicationRequest value)
        {
             ApiResponse<HtmlTemplateApplicationResponse> localVarResponse = await ConvertTemplateApplyHtmlTemplateAsyncWithHttpInfo(value);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Apply HTML template Apply operations to fill in an HTML template, generating a final HTML result
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="value">Operations to apply to template</param>
        /// <returns>Task of ApiResponse (HtmlTemplateApplicationResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<HtmlTemplateApplicationResponse>> ConvertTemplateApplyHtmlTemplateAsyncWithHttpInfo (HtmlTemplateApplicationRequest value)
        {
            // verify the required parameter 'value' is set
            if (value == null)
                throw new ApiException(400, "Missing required parameter 'value' when calling ConvertTemplateApi->ConvertTemplateApplyHtmlTemplate");

            var localVarPath = "/convert/template/html/apply";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (value != null && value.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(value); // http body (model) parameter
            }
            else
            {
                localVarPostBody = value; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ConvertTemplateApplyHtmlTemplate", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<HtmlTemplateApplicationResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (HtmlTemplateApplicationResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(HtmlTemplateApplicationResponse)));
        }

    }
}
